# Generated by Django 5.2.6 on 2025-12-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganicApp', '0005_order_address_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
